# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.


# Site settings
title: TLDSN
brief-intro: 太阳升起时，请重新开始
description: ^^
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tldsn.github.io" # the base hostname & protocol for your site
author: tldsn

permalink: /:year/:month/:day/:title/

# other links
twitter_username: 
facebook_username: 
github_username:  tldsn
email_username: 742720531@qq.com
weibo_username: 5578237033
zhihu_username: yao-yu-jie-90
douban_username: 122400251
cloudmusic_username: 263386850
linkedIn_username: 
dribbble_username:

description_footer:

# comments
duoshuo_shortname: #hygblog
disqus_shortname: https-tldsn-github-io

# statistic analysis 统计代码
baidu_tongji_id: ccd4104a124f2218d64c124431d52789
google_analytics_id: UA-163446273-1

# markdown
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# port
# port: 1234

# url
category_dir: category/
tag_dir: tag/

# excerpt
excerpt_separator: "\n\n\n\n"

#plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate
  
paginate: 5

collections_dir: my_collection

collections:
  authors:
    output: true
  imports:
    output: true
      
# defaults:
#   - scope:
#       path: "/_posts/other/"
#       # type: "authors"
#     values:
#       layout: "author"
#   - scope:
#       path: ""
#       type: "posts"
#     values:
#       layout: "post"
#   - scope:
#       path: ""
#     values:
#       layout: "default"